set_printer_name:
  name: Set Printer Name
  description: >
    Set the name of your printer
  target:
    entity:
      integration: anycubic
  fields:
    name:
      name: Name
      description: Name for your printer
      example: My Printer
      required: true
      selector:
        text:

send_command:
  name: Send a command
  description: >
    Send a command to the printer
  target:
    entity:
      integration: anycubic
  fields:
    command:
      name: Command
      description: Desired command
      required: true
      example: print
      selector:
        select:
          options:
            - print
            - pause
            - resume
            - stop
    file_name:
      name: File number
      description: File name/number to print (Only used for "print" command)
      example: 98.pwms
      required: false
